Huco 125, 131 - Edit Category
Hands-Up-Card-Open/HandsUpForUnity pull request #22
Opened 2022-05-20 19:23 UTC by icechocola05

### Built In Category
![image](https://user-images.githubusercontent.com/59546983/169597265-2e2756aa-3e5e-4791-ad2c-e679ef8b4f19.png)
- cannot edit category name
- make access invisible
### Custom Category
![image](https://user-images.githubusercontent.com/59546983/169597367-7de6b47f-1678-45e1-a2fd-0a88d4cc67d6.png)
![image](https://user-images.githubusercontent.com/59546983/169597393-4533ce8f-9af2-4331-bc78-cd1ac80fb2e4.png)
- user can edit category name and access
- pop up the result of edit
- combine built-in category and custom category, like cards

2022-05-21 04:33 UTC, sleesm requested changes
comment 확인해주시고 수정 부탁드려요!!

2022-05-21 04:33 UTC, sleesm commented on HandsUp/Assets/CardViewScene/Scripts/Category/CategoryManager.cs
> +    public Category GetSpecificCategory(int index)
GetCategory 어떠신가요?

2022-05-21 04:33 UTC, sleesm commented on HandsUp/Assets/CardViewScene/Scripts/CustomManager.cs
> +        selectedCategoryId =  categoryManager.GetSpecificCategory(select.value).GetCategoryId();
GetCategory 어떠신가요?

2022-05-21 04:33 UTC, sleesm commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +        cardManager.DestoryCards();
DestoryCards를 안 불러도 InitCards에서 되지 않나요?

2022-05-21 04:33 UTC, sleesm commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +        bool isInteractable = true;
```suggestion
        bool isInteractable = !category.GetCategoryIsBuiltIn();
```

2022-05-21 04:33 UTC, sleesm commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +    public void InitEditCategories(Category cate)
좋은 방법인 것 같습니다!

2022-05-21 04:33 UTC, sleesm commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +    public void ToggleClick()
이 부분의 경우는 제가 노션에 bug 태그에 올려 둔 toggle 부분을 확인하시면 좋을 것 같습니다!

2022-05-21 04:33 UTC, sleesm commented on HandsUp/Assets/Shared/Scripts/BackBtnManager.cs
> +        if (GameObject.Find("Canvas").transform.Find("CardViewPage/PR_CategoriesScroll").gameObject.activeSelf)
이건 switch문에서 하는 것이 좋을 것 같습니다! CardViewPage가 없는 씬에서는 문제가 발생할 것 같아요

2022-05-22 02:05 UTC, icechocola05 commented on HandsUp/Assets/CardViewScene/Scripts/CustomManager.cs
> +        selectedCategoryId =  categoryManager.GetSpecificCategory(select.value).GetCategoryId();
좋습니다! 수정하겠습니다.

2022-05-22 02:06 UTC, icechocola05 commented on HandsUp/Assets/CardViewScene/Scripts/Category/CategoryManager.cs
> +    public Category GetSpecificCategory(int index)
좋습니다! 수정하겠습니다

2022-05-22 02:06 UTC, icechocola05 commented on HandsUp/Assets/CardViewScene/Scripts/CustomManager.cs
> +        selectedCategoryId =  categoryManager.GetSpecificCategory(select.value).GetCategoryId();
수정하겠습니다

2022-05-22 02:12 UTC, icechocola05 commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +        cardManager.DestoryCards();
카드가 하나도 존재하지 않는 카테고리를 수정했을 때 Destroy가 되지 않아서 추가했는데, InitCards에 조건을 추가하여 수정하도록 하겠습니다

2022-05-22 02:13 UTC, icechocola05 commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +        bool isInteractable = true;
이렇게 쓰는 이유가 있나요? 궁금해서요!

2022-05-22 02:16 UTC, icechocola05 commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +    public void ToggleClick()
확인하고 수정했습니다. 감사합니다.

2022-05-22 02:25 UTC, icechocola05 commented on HandsUp/Assets/Shared/Scripts/BackBtnManager.cs
> +        if (GameObject.Find("Canvas").transform.Find("CardViewPage/PR_CategoriesScroll").gameObject.activeSelf)
PR_CategoriesScroll 이 active 되어 있는 상태여야 Destroy가 가능해서 조건을 바꾸었습니다.
firstView 값을 확인하는 걸로 바꿨는데 확인 부탁드립니다.

2022-05-22 03:55 UTC, sleesm commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +        cardManager.DestoryCards();
넵

2022-05-22 03:55 UTC, sleesm commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +        bool isInteractable = true;
3줄로 쓰이는 걸 한 줄로 바꾸면 좋지 않을까 해서요!

2022-05-22 03:57 UTC, icechocola05 commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +        bool isInteractable = true;
아 이해했습니다! 좋습니다!

2022-05-22 04:00 UTC, sleesm approved these changes
실행이 잘 된다면 머지해도 될 것 같습니다! 다만 제가 멘트 남긴 부분에 대해서 확인 부탁드려요!

2022-05-22 04:00 UTC, sleesm commented on HandsUp/Assets/Shared/Scripts/BackBtnManager.cs
> +        if (GameObject.Find("Canvas").transform.Find("CardViewPage/PR_CategoriesScroll").gameObject.activeSelf)
확인했습니다.

2022-05-22 04:04 UTC, icechocola05 commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +        if(category.GetCategoryIsBuiltIn())
그 부분 수정해서 다시 커밋했는데 확인해주세요!

2022-05-22 04:30 UTC, sleesm commented on HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
> +        if(category.GetCategoryIsBuiltIn())
확인했습니다!

2022-05-22 04:31 UTC, merged