Huco 14&12 - Create edit info and change nickname event function
Hands-Up-Card-Open/HandsUpForUnity pull request #5
Opened 2022-04-06 00:22 UTC by lynne921

### 회원 정보 수정 및 로그인/비로그인 시 닉네임 수정
- 비회원 로그인 버튼 클릭 시 로그인 후 메인 페이지로 이동하며 닉네임 버튼 글자 로그인으로 전환
- 회원 정보 수정 버튼 클릭 시 입력한 정보 서버에게 전달

2022-04-06 02:39 UTC, sleesm requested changes

2022-04-06 02:39 UTC, sleesm commented on HandsUp/Assets/OpeningScene/Scripts/OpeneingManager.cs
> +        GameObject.Find("NickNameBtn").GetComponentInChildren<Text>().text = "�α���";
text에 들어가는 내용이 utf-8이 안된 것 같은데 확인해주세요!!

2022-04-06 02:39 UTC, sleesm commented on HandsUp/Assets/OpeningScene/Scripts/OpeneingManager.cs
> +        userData.userName = userDatas[0].text;
signin 시에는 username이 안들어가는 걸로 알고 있어서 저렇게 표기했는데 왜 바뀌게 되었나요?

2022-04-06 02:39 UTC, sleesm commented on HandsUp/Assets/OpeningScene/Scripts/OpeneingManager.cs
> +        GameObject.Find("NickNameField").GetComponentInChildren<Text>().text = userData.userName;
여기서 idfield와 nicknamefield가 무엇인지 궁금합니다.

2022-04-06 02:39 UTC, sleesm commented on HandsUp/Assets/OpeningScene/Scripts/OpeneingManager.cs
> +            userData.userName = raw;
raw에서 받아와서 값을 넣어주는 건 아직 진행하지 않은 것인가요?

2022-04-06 10:01 UTC, lynne921 commented on HandsUp/Assets/OpeningScene/Scripts/OpeneingManager.cs
> +        GameObject.Find("NickNameField").GetComponentInChildren<Text>().text = userData.userName;
회원정보 수정 화면에서 이메일과 닉네임을 미리 edittext에 뿌려주려고 만들어놓은 것입니다!

2022-04-06 10:56 UTC, sleesm commented on HandsUp/Assets/OpeningScene/Scripts/OpeneingManager.cs
> +        userData.userName = userDataField[0].text;
userDataFiled는 회원가입 시 에 사용하던 걸 그대로 가져오는 것인가요?

2022-04-06 10:56 UTC, sleesm commented on HandsUp/Assets/OpeningScene/Scripts/OpeneingManager.cs
> +        GameObject.Find("NickNameField").GetComponentInChildren<Text>().text = userData.userName;
만약에 그렇다면 미리 텍스트에 표시하고 나서 사용자 입력을 받아와야하는 것 아닌가요?

2022-04-08 14:37 UTC, sleesm commented
@sleesm 이 브랜치 HUCO-44 로 새로 받아서 진행 예정

2022-04-08 14:37 UTC, closed without merging